AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Provisiona a infraestrutura completa para a aplicação Demand Tracker (VPC, EC2, RDS, S3).
  Inclui permissões para conexão via AWS Session Manager (SSM) para contornar firewalls de rede.
  Foco em baixo custo para AWS Academy.

Parameters:
  DBPassword:
    Type: String
    Description: Senha para o banco de dados RDS (mínimo 8 caracteres alfanuméricos).
    NoEcho: true
    MinLength: 8
    AllowedPattern: "[a-zA-Z0-9]+"
  
  SSHKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome do seu par de chaves EC2 existente na região. Necessário para criar a instância, mas não para conectar via SSM.

  MyIP:
    Type: String
    Description: Seu endereço IP (formato CIDR, ex: 187.55.100.20/32). Usado para acesso SSH, se necessário.
    Default: 0.0.0.0/0

Resources:
  # --- 1. REDE (VPC, SUBNETS, GATEWAYS, ROUTING) ---
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PrivateSubnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-IGW
  
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-PublicRouteTable
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # --- 2. GRUPOS DE SEGURANÇA ---
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite SSH (opcional) e acesso a aplicação na porta 5050"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 5050
          ToPort: 5050
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2-SG

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permite acesso MySQL a partir da instância EC2"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !GetAtt EC2SecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDS-SG

  # --- 3. PERMISSÕES PARA A INSTÂNCIA EC2 (PARA CONEXÃO VIA SSM) ---
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-EC2-Role

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # --- 4. S3, EC2, RDS ---
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "demand-tracker-attachments-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
  
  AppServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref SSHKeyName
      # Usando a AMI mais recente do Amazon Linux 2 para a região us-east-1
      ImageId: "ami-0c55b159cbfafe1f0"
      IamInstanceProfile: !Ref EC2InstanceProfile # <-- ANEXA A PERMISSÃO DE SSM
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-AppServer

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group para o RDS"
      SubnetIds:
        - !Ref PrivateSubnet
  
  AppDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${AWS::StackName}-db"
      DBName: demandtrackerdb 
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "8.0"
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false # Mantém os custos baixos
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Database

Outputs:
  EC2PublicIP:
    Description: "IP Público do servidor da aplicação"
    Value: !GetAtt AppServerInstance.PublicIp
  RDSEndpoint:
    Description: "Endpoint do banco de dados RDS"
    Value: !GetAtt AppDatabase.Endpoint.Address
  S3BucketName:
    Description: "Nome do bucket S3 para anexos"
    Value: !Ref AttachmentsBucket